### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by ak3389** [LudoDash/Obs-VCam-Changer#1]
Win10 computer running  C:\Users\Administrator\Desktop\Obs-VCam-Changer-main\obj\Release\net6.0   apphost.exe   No response What's wrong with not opening?

**Comment by LudoDash** [comment]
Sorry i do need more information, im not sure of the problem your having...
Is the application not launching?

**Comment by LudoDash** [comment]
> Win10 computer running C:\Users\Administrator\Desktop\Obs-VCam-Changer-main\obj\Release\net6.0 apphost.exe No response What's wrong with not opening?


Sorry i do need more information, im not sure of the problem your having...
Is the application not launching?

**Comment by LudoDash** [comment]
Issue will be closed in 24hrs if no reply recieved

**Comment by LudoDash** [comment]
New patch released that may solve your issue-
https://github.com/LudoDash/Obs-VCam-Changer/releases/tag/V1.3-Latest-Patch
