### ISSUE TITLE
can you make this work with Avasam  obs-virtual-cam  https://github.com/Avasam/obs-virtual-cam

### ISSUE THREAD

**Issue by Pickymarker** [LudoDash/Obs-VCam-Changer#11]
can you make this work with Avasam
 obs-virtual-cam

https://github.com/Avasam/obs-virtual-cam

**Comment by LudoDash** [comment]
I'll look into it,
Currently busy, so I will work on it in a month's time

**Comment by LudoDash** [comment]
but I highly recommend searching for a different virtual camera plugin as the project you linked it abandoned and it no longer being updated for the latest versions of OBS.

**Comment by Pickymarker** [comment]
the obs plugin i linked is for obs 28
