### ISSUE TITLE
Camera Not Found

### ISSUE THREAD

**Issue by shrimpychip** [LudoDash/Obs-VCam-Changer#12]
I have the newest version of OBS installed and the virtual camera is running, but no camera is showing up in OBS-VCam

**Comment by LudoDash** [comment]
The camera will be there, you may have to scroll up or down, as it also scans for cameras created by an old obs plugin

**Comment by shrimpychip** [comment]
Hey, I did scroll down and there were no cameras listed. I have my OBS virtual camera running plus a logitech webcam plugged in, but 'Kite says 'Wot camera'' is just listed 4 times.

**Comment by LudoDash** [comment]
this software is only designed to rename virtual cameras created by obs, it's not designed to rename real devices.
I may update obsvcam changer to accommodate for newer obs versions, but it's not currently a priority
