### ISSUE TITLE
Regarding the program

### ISSUE THREAD

**Issue by 404oops** [LudoDash/Obs-VCam-Changer#3]
[https://obsproject.com/forum/threads/rename-obs-virtual-camera.135742/](https://obsproject.com/forum/threads/rename-obs-virtual-camera.135742/)
[https://obsproject.com/forum/threads/rename-obs-virtual-cam.137120/](https://obsproject.com/forum/threads/rename-obs-virtual-cam.137120/)
and more have your link. However this is made in C# which is incompatible with macOS and Linux, which people use too.

The camera names and models are also hardcoded into the changer. This is not good for just a name changer

I assume you use C# mainly without any other language. That's mostly fine. However, if you made a compatible version for linux, that would be great.

The first post had a user use macOS, and then you put a Windows-only C# Project onto the post.

I feel like this is a shameless plug and that this behaviour should be eliminated, rectified or reverted

**Comment by LudoDash** [comment]
I will be developing it for macOS eventually.
please understand that,

1: I **cannot** dedicate all of my time to this simple application
2:I Mainly develop for Windows x64
3: C# is compatible with macOS, but I purposely didn't compile a macOS version as the method for changing the camera name is completely different. even if I compiled it for macos it would not run...

The main reason This Application was made,
was a fix for the Omegle camera name detection for VRChat,
which. Only runs on **Windows**.

**Comment by LudoDash** [comment]
> https://obsproject.com/forum/threads/rename-obs-virtual-camera.135742/ https://obsproject.com/forum/threads/rename-obs-virtual-cam.137120/ and more have your link. However this is made in C# which is incompatible with macOS and Linux, which people use too.
> 
> The camera names and models are also hardcoded into the changer. This is not good for just a name changer
> 
> I assume you use C# mainly without any other language. That's mostly fine. However, if you made a compatible version for linux, that would be great.
> 
> The first post had a user use macOS, and then you put a Windows-only C# Project onto the post.
> 
> I feel like this is a shameless plug and that this behaviour should be eliminated, rectified or reverted



I will be developing it for macOS eventually.
please understand that,

1: I **cannot** dedicate all of my time to this simple application
2:I Mainly develop for Windows x64
3: C# is compatible with macOS, but I purposely didn't compile a macOS version as the method for changing the camera name is completely different. even if I compiled it for macos it would not run...

The main reason This Application was made,
was a fix for the Omegle camera name detection for VRChat,
which. Only runs on **Windows**.

**Comment by LudoDash** [comment]
If you so wish, you can Submit Code to the project for MacOS,
but until then just be patient.
