### ISSUE TITLE
Unhandled exception.

### ISSUE THREAD

**Issue by tobi437a** [LudoDash/Obs-VCam-Changer#4]
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at Program.<Mail>$(String[] args)

**Comment by LudoDash** [comment]
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object. at Program.$(String[] args)

Are you able to describe what causes this issue

**Comment by tobi437a** [comment]
Just happens when I open it, idk why

**Comment by LudoDash** [comment]
> Just happens when I open it, idk why

Did you compile the application yourself, or have you used the pre compiled exe in the latest release?

**Comment by tobi437a** [comment]
I used the latest pre compiled exe

**Comment by tobi437a** [comment]
Windows 10

**Comment by LudoDash** [comment]
> Windows 10

Can you send a screenshot of the window that shows the error

**Comment by LudoDash** [comment]
If you are still having issues launching.
Please make sure you have met all of the requirements.

Make sure you have **.NET 6** installed
Make sure you have the latest version of **obs installed / obs virtual camera**

If the application launches and asks for administrator permissions, click **Yes**

If it doesn't launch and ask for administrator permission, then run it as administrator.

Make sure your antivirus is not blocking it,

Mcafee
Avg

And other bad antivirus programs like the above, tend to block many harmless programs.

**Comment by Moiz-I** [comment]
I have the same problem, I've met all the criteria mentioned above, but still the same problem

**Comment by Moiz-I** [comment]
![image](https://user-images.githubusercontent.com/69677514/147370018-4fb9e0cf-1189-4f88-b6f5-4ff9f8461c28.png)

**Comment by Moiz-I** [comment]
![image](https://user-images.githubusercontent.com/69677514/147370050-b1695dcc-07cb-43d2-b7c3-99f8c80dd7a2.png)

**Comment by LudoDash** [comment]
> ![image](https://user-images.githubusercontent.com/69677514/147370050-b1695dcc-07cb-43d2-b7c3-99f8c80dd7a2.png)

Fixed-
releasing Quick patch rn
sorry for the delays.

**Comment by LudoDash** [comment]
New version is- 
https://github.com/LudoDash/Obs-VCam-Changer/releases/tag/V1.3-Latest-Patch
