### ISSUE TITLE
Multi plaform support (macOS/Linux)

### ISSUE THREAD

**Issue by firefinchdev** [LudoDash/Obs-VCam-Changer#6]
Hi
Would be really great and awesome, if you(or someone) could port this to macOS and linux as well..

**Comment by firefinchdev** [comment]
Or maybe you can explain how you achieved renaming the virtual camera. Someone (with required skills) may pick it up.

**Comment by LudoDash** [comment]
Mac os stores data similar to the data in windows registry keys, 
completely different from how windows stores it.
This application was inspired by a game called Vrchat, and commonly people join Omegle in vrchat,
Vrchat is a windows only game, which is one of the many reasons why I never developed the application for MacOS
I may spend time in the future researching how macOS stores/ accesses camera information.
but as of now, this application is windows only sadly.

I do not have access to MacOS laptop, and from quick research.
The latest version of MacOS 12.0 Monterey is not able to be virtualized on a Cpu that isn't the Apple M1 Chip
I am happy to work with you or someone who has some knowledge of MacOS to be able to create a MacOS version.
