### ISSUE TITLE
Whatsapp Desktop is not fooled

### ISSUE THREAD

**Issue by Bluscream** [LudoDash/Obs-VCam-Changer#9]
I wanted to spoof a real device since Whatsapp Desktop does not want virtual video (https://obsproject.com/forum/threads/new-whatsapp-desktop-application-does-not-work-with-obs-virtual-camera.140414/#post-526634)

Sadly changing it to USB Video Device does not allow the cam to be used in Whatsapp

**Comment by LudoDash** [comment]
Hm, yes I see.

I will look into this.

give it a day or two for an update

**Comment by Bluscream** [comment]
> Hm, yes I see.
> 
> I will look into this.
> 
> give it a day or two for an update

Thanks a lot :)

**Comment by LudoDash** [comment]
> > Hm, yes I see.
> > I will look into this.
> > give it a day or two for an update
> 
> Thanks a lot :)



ok, hopefully, this update fixes this issue...

Not sure if it will.
just made the application update the 32x registry which Whatsapp might be reading from

download `Obs_VcamGUI1_3_4(hotfix)` from 
https://github.com/LudoDash/Obs-VCam-Changer/releases

please let me know if it still doesn't work

(also may require a restart of the application/pc to take effect)

**Comment by Bluscream** [comment]
Thanks for the quick potential fix, i will try it as soon as another opportunity arises and report back afterwards.

**Comment by Bluscream** [comment]
Stalebot can be a burden sometimes. (I think theres a label so an issue doesn't go stale)

However we can close this issue as resolved because i didnt have an opportunity to test the fix yet and won't have one in the close future. If the issue happens to come up in the future, this issue can just be re-opened

**Comment by alexandermuehle** [comment]
> Stalebot can be a burden sometimes. (I think theres a label so an issue doesn't go stale)
> 
> However we can close this issue as resolved because i didnt have an opportunity to test the fix yet and won't have one in the close future. If the issue happens to come up in the future, this issue can just be re-opened

I tested and unforunately WhatsApp still doesn't accept the VCam
